version: "3.9"  # optional since v1.27.0
services:
  grafana:
    image: grafana/grafana:8.0.6
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/grafana/datasources/:/etc/grafana/provisioning/datasources
      - ${PWD}/grafana/dashboards/:/etc/grafana/provisioning/dashboards
  influxdb:
    image: influxdb:2.0.7
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=test
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=W-Ds3r25dF3fws8OoyDH6h35Eru0jSrhMYbIP26GiHV8s46GInbcZFnCK1rW0zEhT7tM3s5Iwq2qVAIHGJ3otw==
    ports:
      - 8086:8086
  iothub:
    build:
      context: .
